//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "132.3.2+g4997b2f+chromium-132.0.6834.161";
        public const int CEF_VERSION_MAJOR = 132;
        public const int CEF_COMMIT_NUMBER = 3117;
        public const string CEF_COMMIT_HASH = "4997b2f0c8b83884034ff07a019158cfcef2eea8";
        
        public const int CHROME_VERSION_MAJOR = 132;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 6834;
        public const int CHROME_VERSION_PATCH = 161;
        
        public const string CEF_API_HASH_UNIVERSAL = "3e3393f10c4b95f7516521c8643b9a735fd0c3f3";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "aafe004dac5cf8b7f0b5ef12518c4a16e150f510";
        public const string CEF_API_HASH_PLATFORM_MACOS = "9cd794a0ab4506060ca2d7b3c335778d026337a4";
        public const string CEF_API_HASH_PLATFORM_LINUX = "fab73fe3fddb82c0f75a404fb464935592880803";
    }
}
